version: "3"

services:
  app:
    # Name the image.
    image: rendezqueue_dot_com
    build:
      context: ../../bazel-bin
      # Relative to context.
      dockerfile: ./pkg/rendezqueue.com/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_etc:/etc/letsencrypt

volumes:
  certbot_etc:
    # Name this volume on the host for reuse.
    name: certbot_etc
