version: "3"
services:
  app:
    # Name the image.
    image: rendezqueue_nodejson_http
    build:
      context: ../../src/nodejson/
      # Relative to context.
      dockerfile: ../../deploy/nodejson_http/Dockerfile
    ports:
      - "80:80"
