version: "3"
services:
  nodejs:
    build:
      context: ../../src/nodejson/
      # Relative to context.
      dockerfile: ../../deploy/plain_nodejson/Dockerfile
    image: rendezqueue_plain_nodejson
    ports:
      - "80:80"
