name: Bazel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v1
      with:
        bazel-version: '2.0.0'

    - name: Build
      working-directory: ${{runner.workspace}}
      run: bazel build ...

    - name: Test
      working-directory: ${{runner.workspace}}
      run: bazel test ...
