name: Docker Image

on:
  push:
    branches: ['deploy', 'release']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update_nodejson_http:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: src/nodejson/
        file: pkg/nodejson_http/Dockerfile
        push: true
        tags: ghcr.io/rendezqueue/rendezqueue_nodejson_http:latest

